import type { Content } from "@/types/content";

export const faContent: Content = {
  meta: {
    title: "حمیدرضا درهمی — طراح ارشد محصول",
    description:
      "طراح ارشد محصول. شش سال طراحی پلتفرم‌های سازمانی، اپلیکیشن‌های مصرفی و Design System برای دیوو، سنا، انتخاب هولدینگ و دیگران.",
  },
  hero: {
    name: "حمیدرضا درهمی",
    role: "طراح ارشد محصول و رابط کاربری",
    tagline:
      "طراحی محصول برای من یعنی ایجاد تعادل میان نیاز کاربران، اهداف کسب‌وکار و محدودیت‌های فنی.",
    description:
      "در سال‌های اخیر روی طراحی محصولات و تجربه‌های دیجیتال در صنایع مختلف فعالیت داشته‌ام و در کنار تیم‌های طراحی و توسعه، تلاش کرده‌ام ایده‌های پیچیده را به تجربه‌هایی ساده، قابل استفاده و مقیاس‌پذیر تبدیل کنم.\n\nهمکاری با برندهایی مانند دوو، اسنوا، آردزیا و گروه انتخاب را در قالب فعالیت حرفه‌ای خود در آژانس دیجیتال مارکتینگ سایه تجربه کرده‌ام و در کنار آن، طراحی و اجرای پروژه‌های مستقلی را نیز برای کسب‌وکارهای مختلف بر عهده داشته‌ام.",
    stats: [],
    cta: "مشاهده نمونه‌کارها",
    secondaryCta: "ارتباط با من",
  },
  about: {
    label: "درباره من",
    paragraphs: [
      "برای من طراحی فقط ساختن یک رابط کاربری زیبا نیست.\n\nهر محصول موفق حاصل ایجاد تعادل میان انتظار کاربران، اهداف کسب‌وکار و واقعیت‌های فنی است و همین نگاه، مسیر طراحی من را در تمام پروژه‌ها شکل داده است؛ از شناخت مسئله و طراحی تجربه کاربری گرفته تا طراحی رابط، دیزاین سیستم و همکاری نزدیک با تیم توسعه.\n\nچه در پروژه‌های مستقلی که به صورت مستقیم با کسب‌وکارها همکاری کرده‌ام و چه در پروژه‌هایی که در آژانس دیجیتال مارکتینگ سایه برای برندهایی مانند دوو، اسنوا، آردزیا و گروه انتخاب انجام شده‌اند، همیشه تلاش کرده‌ام راه‌حل‌هایی طراحی کنم که علاوه بر زیبایی، قابل اجرا، کاربردی و ماندگار باشند.",
    ],
  },
  work: {
    label: "نمونه‌کارهای منتخب",
    subtitle: "منتخبی از پروژه‌هایی که در همکاری با برندهای بزرگ و کسب‌وکارهای مستقل انجام شده‌اند.",
    groups: {
      agency: {
        title: "پروژه‌های انجام‌شده در آژانس سایه",
        description: "پروژه‌هایی که در همکاری با آژانس دیجیتال مارکتینگ سایه برای برندهای بزرگ طراحی و اجرا شده‌اند.",
      },
      independent: {
        title: "پروژه‌های فریلنسری در درهمی",
        description: "پروژه‌هایی که به صورت مستقیم برای مشتریان در صنایع مختلف انجام شده‌اند.",
      },
    },
    items: {
      daewoo: {
        title: "دوو",
        subtitle: "تجربه دیجیتال محصولات لوازم خانگی",
        client: "دوو",
        role: "طراح ارشد محصول و رابط کاربری",
        overview: "طراحی تجربه‌های دیجیتال و صفحات فرود کمپین‌های دوو در همکاری با آژانس دیجیتال مارکتینگ سایه.",
        context: "تبدیل نیازهای بازاریابی به تجربه‌هایی ساده، قابل فهم و مؤثر برای کاربران.",
        contribution: "تمرکز بر سلسله‌مراتب بصری، طراحی واکنش‌گرا و مسیرهای کاربری منطبق با اهداف کمپین. طراحی صفحات فرود مقیاس‌پذیر و هماهنگ با هویت برند و اهداف بازاریابی.",
        impact: "ایجاد تجربه‌ای یکپارچه برای کمپین‌های مختلف برند دوو.",
        media: [],
      },
      snowa: {
        title: "اسنوا",
        subtitle: "تجربه دیجیتال محصولات لوازم خانگی",
        client: "اسنوا",
        role: "طراح ارشد محصول و رابط کاربری",
        overview: "طراحی صفحات فرود و تجربه‌های دیجیتال محصولات اسنوا در همکاری با آژانس دیجیتال مارکتینگ سایه.",
        context: "ایجاد تجربه‌ای جذاب در کنار حفظ یکپارچگی هویت برند.",
        contribution: "ترکیب روایت محصول، ساختار محتوایی و طراحی کاربرمحور. طراحی صفحات فرود واکنش‌گرا با ساختار بصری منسجم.",
        impact: "پشتیبانی از کمپین‌های مختلف محصولات اسنوا با تجربه‌ای یکپارچه.",
        media: [],
      },
      ardesia: {
        title: "آردزیا",
        subtitle: "تجربه دیجیتال محصولات آشپزخانه",
        client: "آردزیا",
        role: "طراح ارشد محصول و رابط کاربری",
        overview: "طراحی رابط‌ها و صفحات دیجیتال برند آردزیا در همکاری با آژانس دیجیتال مارکتینگ سایه.",
        media: [],
      },
      entekhab: {
        title: "گروه انتخاب",
        subtitle: "تجربه دیجیتال سازمانی",
        client: "گروه انتخاب",
        role: "طراح ارشد محصول و رابط کاربری",
        overview: "همکاری در طراحی تجربه‌های دیجیتال گروه انتخاب در قالب فعالیت حرفه‌ای در آژانس دیجیتال مارکتینگ سایه.",
        media: [],
      },
      rahampars: {
        title: "رهام پارس",
        subtitle: "وب‌سایت شرکتی",
        client: "رهام پارس",
        role: "طراح UI/UX",
        overview: "طراحی وب‌سایت شرکتی رهام پارس با تمرکز بر ارائه واضح محصولات و خدمات صنعتی.",
        media: [],
      },
      maanpolymer: {
        title: "مان پلیمر",
        subtitle: "وب‌سایت شرکتی",
        client: "مان پلیمر",
        role: "طراح UI/UX",
        overview: "طراحی وب‌سایت شرکتی مان پلیمر با ارائه محصولات پلیمری در قالبی تمیز و حرفه‌ای.",
        media: [],
      },
      fadakargold: {
        title: "فداکارگلد",
        subtitle: "فروشگاه اینترنتی",
        client: "فداکارگلد",
        role: "طراح UI/UX",
        overview: "طراحی فروشگاه اینترنتی فداکارگلد با ایجاد تجربه خرید مطمئن و بصری غنی برای محصولات طلا.",
        media: [],
      },
      adriankesht: {
        title: "آدریان کشت",
        subtitle: "وب‌سایت شرکتی",
        client: "آدریان کشت",
        role: "طراح UI/UX",
        overview: "طراحی وب‌سایت شرکتی آدریان کشت با رابط مدرن و مینیمال برای برند طراحی داخلی.",
        media: [],
      },
      erfanwatch: {
        title: "ارفان واچ",
        subtitle: "فروشگاه اینترنتی",
        client: "ارفان واچ",
        role: "طراح UI/UX",
        overview: "طراحی فروشگاه اینترنتی ارفان واچ با ایجاد تجربه خرید ظریف برای ساعت‌های لوکس.",
        media: [],
      },
    },
  },
  experience: {
    label: "تجربه",
    items: [
      {
        id: "derhami",
        company: "درهمی",
        role: "طراح ارشد محصول و رابط کاربری",
        period: "نوامبر ۲۰۲۱ — اکنون",
        location: "شیراز، ایران",
        type: "فعالیت حرفه‌ای مستقل",
        description:
          "همکاری مستقیم با کسب‌وکارهای مختلف در صنایع گوناگون. طراحی محصولات دیجیتال از مفهوم تا اجرا — شامل پژوهش، طراحی رابط کاربری، دیزاین سیستم و همکاری با تیم توسعه.",
        keyCollabs: ["رهام پارس", "مان پلیمر", "فداکارگلد", "آدریان کشت", "ارفان واچ"],
        skills: ["Product Design", "UI Design", "UX Research", "Design Systems", "Prototyping", "Client Collaboration"],
      },
      {
        id: "shadow",
        company: "آژانس دیجیتال مارکتینگ سایه",
        role: "طراح ارشد محصول و رابط کاربری",
        period: "اکتبر ۲۰۲۴ — اکنون",
        location: "اصفهان، ایران",
        type: "آژانس",
        description:
          "طراحی محصولات دیجیتال کاربرمحور در صنایع فناوری، تجارت الکترونیک و لوازم خانگی. توسعه Design System مقیاس‌پذیر و همکاری نزدیک با توسعه‌دهندگان Front-end.",
        keyCollabs: ["دوو", "اسنوا", "آردزیا", "گروه انتخاب"],
        skills: ["Product Design", "UI Design", "UX Research", "Design Systems", "Developer Collaboration", "Usability Testing"],
      },
    ],
  },
  skills: {
    label: "مهارت‌ها",
    groups: [
      {
        title: "طراحی",
        icon: "palette",
        items: [
          "Product Design",
          "UI Design",
          "UX Research",
          "Design Systems",
          "Prototyping",
          "Interaction Design",
          "Figma",
          "Framer",
        ],
      },
      {
        title: "توسعه",
        icon: "code",
        items: [
          "React / TypeScript",
          "TailwindCSS",
          "HTML / CSS",
          "JavaScript",
          "Git",
          "Responsive Design",
        ],
      },
      {
        title: "فرآیند",
        icon: "workflow",
        items: [
          "Design Strategy",
          "User Research",
          "Workshop Facilitation",
          "Agile / Scrum",
          "Developer Handoff",
          "Accessibility",
        ],
      },
    ],
  },
  contact: {
    headline: "بیایید بسازیم.",
    email: "hi@hawid.ir",
    phone: "+۹۸ ۹۳۳ ۴۸۴ ۷۴۵۲",
    website: "hawid.ir",
    links: [
      {
        label: "تلگرام",
        url: "https://t.me/derhami",
        icon: "message-circle",
      },
      {
        label: "لینکدین",
        url: "https://linkedin.com/in/derhami",
        icon: "link",
      },
      {
        label: "دریبل",
        url: "https://dribbble.com/derhami",
        icon: "heart",
      },
      {
        label: "اینستاگرام",
        url: "https://instagram.com/derhami",
        icon: "globe",
      },
      {
        label: "تریدز",
        url: "https://threads.net/@derhami",
        icon: "link",
      },
      {
        label: "بله",
        url: "https://bale.ai/derhamix",
        icon: "message-circle",
      },
    ],
  },
  labels: {
    nav: {
      home: "خانه",
      work: "کارها",
      experience: "تجربه",
      skills: "مهارت‌ها",
      contact: "تماس",
    },
    modal: {
      close: "بستن",
      visitSite: "مشاهده سایت",
      professionalExperience: "تجربه حرفه‌ای",
      context: "زمینه",
      myContribution: "مشارکت من",
      impact: "تأثیر",
      technologies: "ابزارها",
      links: "لینک‌ها",
      nextProject: "پروژه بعدی",
      previousImage: "تصویر قبلی",
      nextImage: "تصویر بعدی",
      imageAlt: (index: number) => `تصویر ${index + 1}`,
    },
    work: {
      clickToView: "کلیک برای مشاهده",
      visitWebsite: "مشاهده وب‌سایت",
      prevProject: "پروژه قبلی",
      nextProject: "پروژه بعدی",
      projectAlt: (index: number) => `پروژه ${index + 1}`,
    },
    experience: {
      clients: "مشتریان",
    },
    assistant: {
      openLabel: "باز کردن دستیار",
      dialogLabel: "دستیار هوشمند",
      terminalTitle: "assistant@derhami:~",
      welcomeMessage: "> سلام! من دستیار هوشمند حمیدرضا هستم. سوالات متداول مشتریان اینجاست یا تایپ کنید:",
      moreQuestions: "سوالات دیگر",
      emailButton: "ایمیل",
      emailSubject: "سوال از دستیار هوشمند",
      emailQuestionPrefix: "سوال:",
      emailAnswerPrefix: "پاسخ:",
      emailMessagePrefix: "---\nپیام شما:",
      placeholder: "تایپ کنید...",
      backToQuestions: "بازگشت به سوالات",
      close: "بستن",
    },
    capsule: {
      sectionNav: "ناوبری بخش‌ها",
      toggleTheme: "تغییر تم",
      themeLight: "روشن",
      themeDark: "تیره",
      toggleLanguage: "تغییر زبان",
      langEn: "ان",
      langFa: "فا",
      openMenu: "باز کردن منو",
      closeMenu: "بستن منو",
    },
  },
  seo: {
    title: "حمیدرضا درهمی — طراح ارشد محصول",
    description:
      "طراح ارشد محصول. شش سال طراحی پلتفرم‌های سازمانی، اپلیکیشن‌های مصرفی و Design System برای دیوو، سنا، انتخاب هولدینگ و دیگران.",
    author: "حمیدرضا درهمی",
    ogTitle: "حمیدرضا درهمی — طراح ارشد محصول",
    ogDescription:
      "شش سال طراحی پلتفرم‌های سازمانی، اپلیکیشن‌های مصرفی و Design System.",
    ogUrl: "https://hawid.ir",
    ogSiteName: "حمیدرضا درهمی",
    jsonLd: {
      "@context": "https://schema.org",
      "@type": "Person",
      name: "حمیدرضا درهمی",
      url: "https://hawid.ir",
      jobTitle: "طراح ارشد محصول",
      email: "hi@hawid.ir",
      sameAs: [
        "https://linkedin.com/in/derhami",
        "https://dribbble.com/derhami",
      ],
    },
  },
};
